document.addEventListener("DOMContentLoaded",()=>{
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const header=$(".header");
if(header){const t=()=>header.classList.toggle("scrolled",window.scrollY>80);t();window.addEventListener("scroll",t,{passive:true});}
const whatsappDropdown=$(".whatsapp-dropdown"),whatsappToggle=$(".whatsapp-toggle"),whatsappMenu=$(".whatsapp-menu");
if(whatsappDropdown&&whatsappToggle&&whatsappMenu){whatsappToggle.addEventListener("click",e=>{e.stopPropagation();whatsappDropdown.classList.toggle("active");});whatsappMenu.addEventListener("click",e=>e.stopPropagation());document.addEventListener("click",()=>whatsappDropdown.classList.remove("active"));document.addEventListener("keydown",e=>{if(e.key==="Escape")whatsappDropdown.classList.remove("active");});}
const suitTabs=$$(".suit-tab"),suitLines=$$(".suit-line");
const showSuitLine=linea=>{suitLines.forEach(line=>line.classList.toggle("active",line.dataset.lineaContent===linea));suitTabs.forEach(tab=>tab.classList.toggle("active",tab.dataset.linea===linea));};
if(suitTabs.length&&suitLines.length){suitTabs.forEach(tab=>tab.addEventListener("click",()=>showSuitLine(tab.dataset.linea)));showSuitLine("linea1");}
const lightbox=$("#imageLightbox");
if(lightbox){const img=lightbox.querySelector("img"),close=lightbox.querySelector(".lightbox-close");$$(".suit-gallery-compact img").forEach(i=>i.addEventListener("click",()=>{img.src=i.src;img.alt=i.alt;lightbox.classList.add("active");}));close?.addEventListener("click",()=>lightbox.classList.remove("active"));lightbox.addEventListener("click",e=>{if(e.target===lightbox)lightbox.classList.remove("active");});}
const editor2dCanvas=$("#editor2dCanvas"),suitStage=$("#suitStage"),textLayer=$("#editorTextLayer"),customLayer=$("#editorCustomLayer");
const selectedPieceName=$("#selectedPieceName"),selectedZoneName=$("#selectedZoneName"),pieceColor=$("#pieceColor"),riderName=$("#riderName"),riderNumber=$("#riderNumber"),currentViewLabel=$("#editorCurrentViewLabel");
const logoUpload=$("#logoUpload"),addLogoBtn=$("#addLogoBtn"),addTextBtn=$("#addTextBtn"),exportDesignBtn=$("#exportDesignBtn"),applyPieceBtn=$("#applyPieceBtn"),applyZoneBtn=$("#applyZoneBtn");
let currentView="front",selectedPiece=null,hoveredPiece=null,selectedZone="base",selectedDesignItem=null;
let renderedPieces=[],customItems=[];
const pieceColors={};
const isMobile=window.matchMedia("(max-width: 820px), (pointer: coarse)").matches;
const mobileAlphaMax=760;
const viewLabels={front:"Frontal",back:"Trasero",perfil:"Perfil"};
const zoneLabels={base:"Base cuero",torso:"Torso",arms:"Brazos",legs:"Piernas",details:"Detalles",protection:"Protecciones"};
const presets={
killian:{base:"#111111",torso:"#5bd43b",arms:"#111111",legs:"#5bd43b",details:"#f1f1f1",protection:"#2b2b2b"},
viper:{base:"#090909",torso:"#3b3b3b",arms:"#111111",legs:"#2a2a2a",details:"#5bd43b",protection:"#e9e9e9"},
racing:{base:"#111111",torso:"#c1121f",arms:"#ffffff",legs:"#c1121f",details:"#ffffff",protection:"#222222"}
};
const cleanName=name=>String(name||"Pieza").replace(/[-_]/g," ").replace(/\s+/g," ").trim().replace(/\b\w/g,c=>c.toUpperCase());
const getZone=piece=>{
const n=String(piece.name||piece.id||"").toLowerCase();
if(/rodilla|numero|cierre|cuello|trapecio/.test(n))return "details";
if(/pantorrilla|pierna|espinilla/.test(n))return "legs";
if(/brazo|antebrazo|hombro/.test(n))return "arms";
if(/pecho|espalda|tronco|cintura|lateral|back/.test(n))return "torso";
if(/prote|slider|tank/.test(n))return "protection";
return "base";
};
const hexToHue=hex=>{const v=String(hex||"").replace("#","");if(v.length!==6)return 0;const r=parseInt(v.slice(0,2),16)/255,g=parseInt(v.slice(2,4),16)/255,b=parseInt(v.slice(4,6),16)/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d===0)h=0;else if(max===r)h=60*(((g-b)/d)%6);else if(max===g)h=60*(((b-r)/d)+2);else h=60*(((r-g)/d)+4);return Math.round(h<0?h+360:h);};
const colorFilter=color=>{if(!color||color==="#ffffff")return "brightness(1.08) contrast(1.05)";if(color==="#111111"||color==="#000000"||color==="#090909")return "brightness(.18) contrast(1.5) saturate(.75)";return `sepia(1) saturate(6.5) hue-rotate(${hexToHue(color)}deg) brightness(.9) contrast(1.08)`;};
const imageCandidates=(view,piece)=>{const names=[piece.file,piece.src,piece.name&&`${piece.name}.png`,piece.name&&`${piece.name}.webp`].filter(Boolean);const unique=[...new Set(names)];const paths=[];unique.forEach(name=>{paths.push(`images/${view}/${name}`,`images/${name}`,`images/piezas/${view}/${name}`,`images/piezas/${name}`);});return [...new Set(paths)];};
const loadWithFallback=(img,paths,i=0)=>{if(i>=paths.length){img.dataset.missing="true";console.warn("No se encontró imagen:",img.alt,paths);return;}img.onerror=()=>loadWithFallback(img,paths,i+1);img.src=paths[i];};
const buildAlphaCtx=img=>{const iw=img.naturalWidth||1,ih=img.naturalHeight||1;const limit=isMobile?mobileAlphaMax:Math.max(iw,ih);const scale=Math.min(1,limit/Math.max(iw,ih));const c=document.createElement("canvas");c.width=Math.max(1,Math.round(iw*scale));c.height=Math.max(1,Math.round(ih*scale));const ctx=c.getContext("2d",{willReadFrequently:true});ctx.drawImage(img,0,0,c.width,c.height);ctx._alphaScale=scale;return ctx;};
const getImageDrawRect=img=>{const r=editor2dCanvas.getBoundingClientRect(),iw=img.naturalWidth||1,ih=img.naturalHeight||1,scale=Math.min(r.width/iw,r.height/ih),w=iw*scale,h=ih*scale,x=(r.width-w)/2,y=(r.height-h)/2;return{x,y,w,h,iw,ih};};
const pointOnImage=(e,img)=>{const r=editor2dCanvas.getBoundingClientRect(),d=getImageDrawRect(img),x=e.clientX-r.left-d.x,y=e.clientY-r.top-d.y;if(x<0||y<0||x>d.w||y>d.h)return null;return{x:Math.max(0,Math.min(d.iw-1,Math.floor(x/d.w*d.iw))),y:Math.max(0,Math.min(d.ih-1,Math.floor(y/d.h*d.ih)))};};
const hitTest=e=>{for(let i=renderedPieces.length-1;i>=0;i--){const item=renderedPieces[i];if(item.editable===false||!item.alphaCtx||!item.el.complete)continue;const p=pointOnImage(e,item.el);if(!p)continue;const sx=item.alphaCtx.canvas.width/(item.el.naturalWidth||1);const sy=item.alphaCtx.canvas.height/(item.el.naturalHeight||1);const ax=Math.max(0,Math.min(item.alphaCtx.canvas.width-1,Math.floor(p.x*sx)));const ay=Math.max(0,Math.min(item.alphaCtx.canvas.height-1,Math.floor(p.y*sy)));const alpha=item.alphaCtx.getImageData(ax,ay,1,1).data[3];if(alpha>12)return item;}return null;};
const clearActivePieces=()=>renderedPieces.forEach(p=>p.el.classList.remove("active"));
const clearHover=()=>renderedPieces.forEach(p=>p.el.classList.remove("hovered"));
const setActiveZone=z=>{selectedZone=z||"base";$$(".zone-btn").forEach(b=>b.classList.toggle("active",b.dataset.zone===selectedZone));if(selectedZoneName)selectedZoneName.textContent=zoneLabels[selectedZone]||selectedZone;};
const selectPiece=item=>{clearActivePieces();selectedPiece=item;if(!item){selectedPieceName&&(selectedPieceName.textContent="Ninguna");selectedZoneName&&(selectedZoneName.textContent=zoneLabels[selectedZone]||selectedZone);return;}item.el.classList.add("active");selectedPieceName&&(selectedPieceName.textContent=cleanName(item.name||item.id));setActiveZone(item.zone);pieceColor&&(pieceColor.value=pieceColors[item.id]||item.color||"#ffffff");};
const applyColor=(item,color)=>{if(!item||!color||item.editable===false)return;pieceColors[item.id]=color;item.color=color;item.el.style.filter=colorFilter(color);pieceColor&&(pieceColor.value=color);};
const applyColorToZone=(zone,color)=>renderedPieces.forEach(item=>{if(item.zone===zone&&item.editable!==false)applyColor(item,color);});
const applyPreset=name=>{const preset=presets[name]||presets.killian;renderedPieces.forEach(item=>{if(item.editable!==false)applyColor(item,preset[item.zone]||preset.base);});pieceColor&&(pieceColor.value=preset[selectedZone]||preset.base);};
const renderTextOverlays=()=>{if(!textLayer)return;textLayer.innerHTML="";const name=(riderName?.value||"").trim().toUpperCase(),num=(riderNumber?.value||"").trim();if(name){const el=document.createElement("div");el.className="editor-name-text";el.textContent=name;textLayer.appendChild(el);}if(num&&(currentView==="back"||currentView==="perfil")){const el=document.createElement("div");el.className="editor-number-text";el.textContent=num;textLayer.appendChild(el);}};
const renderEditorView=view=>{if(!editor2dCanvas||!suitStage||!window.KILLIAN_PIECES)return;currentView=view;selectedPiece=null;hoveredPiece=null;renderedPieces.forEach(item=>{item.alphaCtx=null;if(item.el)item.el.onload=item.el.onerror=null;});renderedPieces=[];suitStage.innerHTML="";editor2dCanvas.dataset.view=view;currentViewLabel&&(currentViewLabel.textContent=viewLabels[view]||view);selectedPieceName&&(selectedPieceName.textContent="Ninguna");const allPieces=window.KILLIAN_PIECES[view]||[];const pieces=isMobile?allPieces.filter(p=>p.base||p.editable!==false&&!p.helper):allPieces;pieces.forEach((piece,index)=>{const img=document.createElement("img");img.alt=piece.name||piece.id||`pieza-${index}`;img.className=`suit-piece ${piece.editable===false?"support-piece":"editable-piece"}`;img.dataset.id=piece.id||`${view}_${index}`;img.draggable=false;img.loading="eager";img.decoding="async";img.style.zIndex=index+1;const id=img.dataset.id,zone=getZone(piece),color=pieceColors[id]||"#ffffff";const item={...piece,id,zone,el:img,alphaCtx:null,color};if(item.editable!==false)img.style.filter=colorFilter(color);img.addEventListener("load",()=>{try{if(item.editable!==false)item.alphaCtx=buildAlphaCtx(img);}catch(err){console.warn("No se pudo leer alpha:",img.alt,err);}});renderedPieces.push(item);suitStage.appendChild(img);loadWithFallback(img,imageCandidates(view,piece));});renderTextOverlays();setTimeout(()=>applyPreset($$(".preset-card.active")[0]?.dataset.preset||"killian"),180);};
if(editor2dCanvas&&suitStage&&window.KILLIAN_PIECES){renderEditorView("front");const pick=e=>{if(e.target.closest(".design-item"))return;selectPiece(hitTest(e));};editor2dCanvas.addEventListener("click",pick);editor2dCanvas.addEventListener("touchend",e=>{if(e.changedTouches&&e.changedTouches[0])pick(e.changedTouches[0]);},{passive:true});if(!isMobile){editor2dCanvas.addEventListener("mousemove",e=>{const item=hitTest(e);if(item===hoveredPiece)return;clearHover();hoveredPiece=item;editor2dCanvas.classList.toggle("can-select",!!item);if(item)item.el.classList.add("hovered");});editor2dCanvas.addEventListener("mouseleave",()=>{clearHover();hoveredPiece=null;editor2dCanvas.classList.remove("can-select");});}}
$$(".view-btn").forEach(btn=>btn.addEventListener("click",()=>{$$(".view-btn").forEach(b=>b.classList.remove("active"));btn.classList.add("active");renderEditorView(btn.dataset.view||"front");}));
$$(".editor-tab").forEach(tab=>tab.addEventListener("click",()=>{$$(".editor-tab").forEach(t=>t.classList.remove("active"));$$('.editor-panel-section').forEach(p=>p.classList.remove("active"));tab.classList.add("active");$(`[data-panel-content="${tab.dataset.panel}"]`)?.classList.add("active");}));
$$(".zone-btn").forEach(btn=>btn.addEventListener("click",()=>{setActiveZone(btn.dataset.zone);pieceColor&&(pieceColor.value=presets[$$(".preset-card.active")[0]?.dataset.preset||"killian"][selectedZone]||"#ffffff");}));
$$(".preset-card").forEach(btn=>btn.addEventListener("click",()=>{$$(".preset-card").forEach(b=>b.classList.remove("active"));btn.classList.add("active");applyPreset(btn.dataset.preset);}));
pieceColor?.addEventListener("input",()=>{if(selectedPiece)applyColor(selectedPiece,pieceColor.value);else applyColorToZone(selectedZone,pieceColor.value);});
applyPieceBtn?.addEventListener("click",()=>selectedPiece&&applyColor(selectedPiece,pieceColor.value));
applyZoneBtn?.addEventListener("click",()=>applyColorToZone(selectedZone,pieceColor.value));
riderName?.addEventListener("input",renderTextOverlays);riderNumber?.addEventListener("input",renderTextOverlays);
const selectDesignItem=el=>{customItems.forEach(item=>item.el.classList.remove("selected"));selectedDesignItem=el||null;if(selectedDesignItem)selectedDesignItem.classList.add("selected");};
const makeDraggable=el=>{let sx=0,sy=0,left=0,top=0,drag=false;const move=e=>{if(!drag)return;e.preventDefault?.();const p=e.touches?e.touches[0]:e,r=editor2dCanvas.getBoundingClientRect();el.style.left=`${Math.max(0,Math.min(92,left+(p.clientX-sx)/r.width*100))}%`;el.style.top=`${Math.max(0,Math.min(92,top+(p.clientY-sy)/r.height*100))}%`;};const end=()=>{drag=false;document.removeEventListener("mousemove",move);document.removeEventListener("mouseup",end);document.removeEventListener("touchmove",move);document.removeEventListener("touchend",end);};const start=e=>{selectDesignItem(el);drag=true;const p=e.touches?e.touches[0]:e;sx=p.clientX;sy=p.clientY;left=parseFloat(el.style.left)||50;top=parseFloat(el.style.top)||50;document.addEventListener("mousemove",move);document.addEventListener("mouseup",end);document.addEventListener("touchmove",move,{passive:false});document.addEventListener("touchend",end);};el.addEventListener("mousedown",start);el.addEventListener("touchstart",start,{passive:false});};
const addCustomText=(text="KILLIAN")=>{if(!customLayer)return;const el=document.createElement("div");el.className="design-item design-text";el.textContent=prompt("Texto a agregar:",text)||text;el.style.left="42%";el.style.top="48%";el.style.width="18%";el.style.height="8%";customLayer.appendChild(el);customItems.push({type:"text",el});makeDraggable(el);selectDesignItem(el);};
const addCustomLogo=src=>{if(!customLayer)return;const el=document.createElement("div");el.className="design-item design-logo";el.style.left="42%";el.style.top="38%";el.style.width="18%";el.style.height="16%";const img=document.createElement("img");img.src=src;img.alt="Logo personalizado";el.appendChild(img);customLayer.appendChild(el);customItems.push({type:"logo",el});makeDraggable(el);selectDesignItem(el);};
addTextBtn?.addEventListener("click",()=>addCustomText());
addLogoBtn?.addEventListener("click",()=>logoUpload?.click());
logoUpload?.addEventListener("change",e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>addCustomLogo(reader.result);reader.readAsDataURL(file);logoUpload.value="";});
document.addEventListener("keydown",e=>{if((e.key==="Delete"||e.key==="Backspace")&&selectedDesignItem){customItems=customItems.filter(i=>i.el!==selectedDesignItem);selectedDesignItem.remove();selectedDesignItem=null;}});
exportDesignBtn?.addEventListener("click",async()=>{if(!window.html2canvas){alert("No cargó html2canvas. Revisa tu conexión o el CDN.");return;}exportDesignBtn.disabled=true;exportDesignBtn.textContent="Exportando...";try{const canvas=await html2canvas(editor2dCanvas,{backgroundColor:null,useCORS:true,scale:isMobile?1.2:2});const a=document.createElement("a");a.download=`killian-diseno-${currentView}.png`;a.href=canvas.toDataURL("image/png");a.click();}catch(err){console.error(err);alert("No pude exportar el PNG. Revisa que las imágenes estén en el mismo dominio.");}finally{exportDesignBtn.disabled=false;exportDesignBtn.textContent="Exportar PNG";}});
setActiveZone("base");
});
