window.KILLIAN_PIECES = [
  {id:1,name:"antebrazo-1 2",file:"antebrazo-1 2.webp"},
  {id:2,name:"antebrazo-1",file:"antebrazo-1.webp"},
  {id:3,name:"antebrazo-2 2",file:"antebrazo-2 2.webp"},
  {id:4,name:"antebrazo-2",file:"antebrazo-2.webp"},
  {id:5,name:"antebrazo-l",file:"antebrazo-l.webp"},
  {id:6,name:"antebrazo-r",file:"antebrazo-r.webp"},
  {id:7,name:"back",file:"back.webp"},
  {id:8,name:"Background",file:"Background.webp"},
  {id:9,name:"Back-view",file:"Back-view.webp"},
  {id:10,name:"brazo 1 2",file:"brazo 1 2.webp"},
  {id:11,name:"brazo 1",file:"brazo 1.webp"},
  {id:12,name:"brazo 2",file:"brazo 2.webp"},
  {id:13,name:"brazo 3",file:"brazo 3.webp"},
  {id:14,name:"brazo-2",file:"brazo-2.webp"},
  {id:15,name:"brazo-externo-l",file:"brazo-externo-l.webp"},
  {id:16,name:"brazo-externo-r",file:"brazo-externo-r.webp"},
  {id:17,name:"brazo-interno-l",file:"brazo-interno-l.webp"},
  {id:18,name:"brazo-interno-r",file:"brazo-interno-r.webp"},
  {id:19,name:"brazo-l",file:"brazo-l.webp"},
  {id:20,name:"brazo-l-2",file:"brazo-l-2.webp"},
  {id:21,name:"brazo-l-3",file:"brazo-l-3.webp"},
  {id:22,name:"brazo-r",file:"brazo-r.webp"},
  {id:23,name:"brazo-r-2",file:"brazo-r-2.webp"},
  {id:24,name:"brazo-r-3",file:"brazo-r-3.webp"},
  {id:25,name:"cierre 2",file:"cierre 2.webp"},
  {id:26,name:"cierre",file:"cierre.webp"},
  {id:27,name:"cintura 2",file:"cintura 2.webp"},
  {id:28,name:"cintura",file:"cintura.webp"},
  {id:29,name:"cuello-l 2",file:"cuello-l 2.webp"},
  {id:30,name:"cuello-l",file:"cuello-l.webp"},
  {id:31,name:"cuello-r 2",file:"cuello-r 2.webp"},
  {id:32,name:"cuello-r",file:"cuello-r.webp"},
  {id:33,name:"espalda 2",file:"espalda 2.webp"},
  {id:34,name:"espalda 3",file:"espalda 3.webp"},
  {id:35,name:"espalda 4",file:"espalda 4.webp"},
  {id:36,name:"espalda",file:"espalda.webp"},
  {id:37,name:"lateral-l 2",file:"lateral-l 2.webp"},
  {id:38,name:"lateral-l",file:"lateral-l.webp"},
  {id:39,name:"lateral-r 2",file:"lateral-r 2.webp"},
  {id:40,name:"lateral-r",file:"lateral-r.webp"},
  {id:41,name:"numero-espalda",file:"numero-espalda.webp"},
  {id:42,name:"numero-espalda-base",file:"numero-espalda-base.webp"},
  {id:43,name:"paleta",file:"paleta.webp"},
  {id:44,name:"pantorrilla 2 2",file:"pantorrilla 2 2.webp"},
  {id:45,name:"pantorrilla 2",file:"pantorrilla 2.webp"},
  {id:46,name:"pantorrilla",file:"pantorrilla.webp"},
  {id:47,name:"pantorrilla-l 2",file:"pantorrilla-l 2.webp"},
  {id:48,name:"pantorrilla-l 3",file:"pantorrilla-l 3.webp"},
  {id:49,name:"pantorrilla-l",file:"pantorrilla-l.webp"},
  {id:50,name:"pantorrilla-r",file:"pantorrilla-r.webp"},
  {id:51,name:"pecho 2",file:"pecho 2.webp"},
  {id:52,name:"pecho",file:"pecho.webp"},
  {id:53,name:"perfil-view",file:"perfil-view.webp"},
  {id:54,name:"pierna 2",file:"pierna 2.webp"},
  {id:55,name:"pierna",file:"pierna.webp"},
  {id:56,name:"pierna-1 2",file:"pierna-1 2.webp"},
  {id:57,name:"pierna-1",file:"pierna-1.webp"},
  {id:58,name:"pierna-2 2",file:"pierna-2 2.webp"},
  {id:59,name:"pierna-2",file:"pierna-2.webp"},
  {id:60,name:"pierna-3 2",file:"pierna-3 2.webp"},
  {id:61,name:"pierna-3",file:"pierna-3.webp"},
  {id:62,name:"pierna-l 2",file:"pierna-l 2.webp"},
  {id:63,name:"pierna-l",file:"pierna-l.webp"},
  {id:64,name:"pierna-l2",file:"pierna-l2.webp"},
  {id:65,name:"pierna-l3",file:"pierna-l3.webp"},
  {id:66,name:"pierna-r2",file:"pierna-r2.webp"},
  {id:67,name:"pierna-r3",file:"pierna-r3.webp"},
  {id:68,name:"preview",file:"preview.webp"},
  {id:69,name:"rodilla-l",file:"rodilla-l.webp"},
  {id:70,name:"rodilla-r 2",file:"rodilla-r 2.webp"},
  {id:71,name:"rodilla-r",file:"rodilla-r.webp"},
  {id:72,name:"rodillas-l",file:"rodillas-l.webp"},
  {id:73,name:"traje2",file:"traje2.webp"},
  {id:74,name:"traje-f",file:"traje-f.webp"},
  {id:75,name:"trapecio-l",file:"trapecio-l.webp"},
  {id:76,name:"trapecio-r",file:"trapecio-r.webp"},
  {id:77,name:"trapecios",file:"trapecios.webp"},
  {id:78,name:"tronco-inferior 2",file:"tronco-inferior 2.webp"},
  {id:79,name:"tronco-inferior",file:"tronco-inferior.webp"}
  ];
];
